### ISSUE TITLE
max_latent_action seems never being passed in

### ISSUE THREAD

**Issue by Mohan-Zhang-u** [Wenxuan-Zhou/PLAS#1]
Hi Wenxuan, your work is amazing and thanks a lot for publishing the code!! There is one question that I found confusing while reading your code, and I would greatly appreciate your replies, if possible:
it seems in your main.py, you only defined the hyperparameter max_latent_action, but never passed it in algo.py or anywhere else. 

You do set the default value of max_latent_action of class ActorPerturbation, Latent and LatentPerturbation to 2 (which however cannot be changed by passing in commandline arguments)

If I'm understanding it correctly, you ultimately want ActorPerturbation to have max_latent_action, to get the latent_action in the forward pass and then decode the latent_action with the VAE decoder to get the real action multiplied with a phi as the perturbation?

Also here,
https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/main.py#L107
If I'm reading correctly, according to your paper, your VAE should take max_latent_action instead of max_action as an argument, since it is responsible for the latent space, which has nothing to do with the real actions, in my opinion.

Thank you again for your splendid work and hopefully I could get some help in understanding it! Have a nice weekend!

**Comment by Wenxuan-Zhou** [comment]
Hi Mohan,

1. args.max_latent_action is passed into the policy using **vars(args):
https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/main.py#L124
https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/main.py#L126

2. ActorPerturbation has two parts. The first part is the same as the Latent policy which outputs a latent action (limited by tanh and scaled by max_latent_action, [L54](https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/algos.py#L54)) and passes it to the decoder to get a real action which I called mid_action([L56](https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/algos.py#L56)). The second part is to output a residual (limited by tanh and scaled by phi, [L60](https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/algos.py#L60)). The residual will be added to the mid_action to generate a final action output ([L61](https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/algos.py#L61)).

3. In our method, VAE is used to reconstruct actions. Max_action is used for reconstruction ([L138](https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/algos.py#L138)), not for the latent space. The latent space of the VAE itself is constrained to be close to a normal distribution using [KL loss](https://github.com/Wenxuan-Zhou/PLAS/blob/39e64f0a4716c3ad36b612be04f344a72c959a64/algos.py#L165). Max_latent_action is a property of the Latent Policy instead of the VAE itself. We train a VAE to get a latent space, and then the Latent Policy can choose within a smaller range within the whole latent space, given by the max_latent_action.

I hope this helps. Feel free to follow up if you have any other questions!

**Comment by Mohan-Zhang-u** [comment]
Hi Wenxuan,
  Thanks a lot for your detailed reply and I'm terribly sorry for the late reply! They solved my questions and thank you again for your kindness and great work!
